spring:
  datasource:
    url: ${POSTGRES_URL_ORDER_SERVICE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

user:
  service:
    url: http://localhost:8081