name: CI Pipeline

on:
  push:
    branches:
      - main
      - order-service

jobs:
  build-test-sonarqube-docker:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${{secrets.POSTGRES_URL_DOCKER}}
      SPRING_DATASOURCE_USERNAME: ${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${{secrets.SPRING_KAFKA_BOOTSTRAP_SERVERS}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      USER_SERVICE_URL: ${{secrets.USER_SERVICE_URL}}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install PostgreSQL client
        run: sudo apt update && sudo apt install -y postgresql-client

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres -q && break
            echo "Waiting..."
            sleep 2
          done

      - name: Run tests
        run: mvn test

      - name: SonarQube analysis
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=oldvabik_marketplace-order-service \
          -Dsonar.organization=oldvabik \
          -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} \
          -Dsonar.login=${{secrets.SONAR_TOKEN}}

      - name: Build Docker image
        run: |
          docker build -t orderservice-app .      
          docker save orderservice-app -o orderservice-app.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: orderservice-docker-image
          path: ./orderservice-app.tar
